name: Issues ejemplo

on:
  issues:
    types: [opened]

jobs:
  procesa-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra el t√≠tulo del issue
        run: echo "El titulo del issue es '${{ github.event.issue.title }}'"
